name: Netflix Party Harder

options:
  bundleIdPrefix: com.nflx-partiers
  settings:
    DEBUG_INFORMATION_FORMAT: DWARF
targets:
  actionstest:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources: [ios]
    attributes: []
    settings:
      DEBUG_INFORMATION_FORMAT: DWARF
