name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Change directory to Flutter app
      run: cd flutter_app
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
