name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  steebchen/flutter@v1.0.0

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: cd flutter_app && pub get
    - name: Run tests
      run: cd flutter_app && pub run test
