name: Release

on:
  push:
    branches: [ master, test-deploy ]
    tags: 
      - 'release'
    paths:
      - 'flutter_app/**'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Build
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.9'
      - run: cd flutter_app && flutter pub get
      - run: cd flutter_app && flutter build ios --release --no-codesign
      - name: Run fastlane deploy
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'beta'
          subdirectory: './flutter_app/ios'
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD}}
          APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_SESION: ${{ secrets.FASTLANE_SESSION }}
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
